# Basic Auth Configurations
username:
password:

# Basic Configurations
browser_driver_path: ./driver/chromedriver.exe
basic_url: https://visa.vfsglobal.com/ind/en/

# Login Configurations
captcha_path: ./driver/captcha.png
captcha_success_path: ./driver/captcha_success.png
captcha_click_path: ./driver/captcha_click.png
