# Basic Auth Configurations
username:
password:

# Basic Configurations
browser_driver_path: ./driver/chromedriver.exe
basic_url: https://visa.vfsglobal.com/ind/en/
make_appointment_xpath: //*[@id="__layout"]/div/main/div/div/div[3]/div/p[29]/a
username_xpath: //*[@id="mat-input-0"]
password_xpath: //*[@id="mat-input-1"]
captcha_path: ./driver/captcha.png
captcha_click_path: ./driver/captcha_click.png
submit_xpath: /html/body/app-root/div/div/app-login/section/div/div/mat-card/form/button